# Generated by Django 5.2.5 on 2025-08-21 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_livro_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1111), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
